apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: r0h9ukpxd-python 
  janus-idp.io/tekton: r0h9ukpxd-python
  backstage.io/kubernetes-id: r0h9ukpxd-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: r0h9ukpxd-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml