apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: r0h9ukpxd-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:59914a1bb4fb1c340bef5a844c75e96d47cb7282@sha256:db1cc3df1debe4ebf64137eae4c28c711be7168c4c5fe0991a6982e246d120b0
          name: container-image
